/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Getting Started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Building Apps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Building Apps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrating with SEMOSS',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Integrating with SEMOSS',
        },
      ],
    },
    {
      type: 'category',
      label: 'Understanding Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Understanding Development',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Installation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Advanced Installation',
        },
      ],
    },
    {
      type: 'category',
      label: 'How To',
      items: [
        {
          type: 'autogenerated',
          dirName: 'How To',
        },
      ],
    },
    {
      type: 'category',
      label: 'Cookbook Recipes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cookbook Recipes',
        },
      ],
    },
     {
      type: 'category',
      label: 'Reactor',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ReactorsRefactor',
        },
      ],
    },
    {
      type: "category",
      label: "AI Core API",
      link: {
        type: "generated-index",
        title: "AI Core API",
        description:
          "This is a sample server AI-Core server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/ai-core-api"
      },
      items: require("./docs/ai-core-api/sidebar.ts")
    }
  ],

}

export default sidebars;
