import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "ai-core-api/ai-core",
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "doc",
          id: "ai-core-api/get-json-output",
          label: "getJSONOutput",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Authorization",
      items: [
        {
          type: "doc",
          id: "ai-core-api/search-for-user",
          label: "Search for users",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Engine Route",
      items: [
        {
          type: "doc",
          id: "ai-core-api/image-download",
          label: "Download engine image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/update-smss-file",
          label: "Update engine SMSS file",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Database Engine",
      items: [
        {
          type: "doc",
          id: "ai-core-api/image-download-1",
          label: "Download database image (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/update-smss-file-1",
          label: "Update database SMSS file (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "MCP",
      items: [
        {
          type: "doc",
          id: "ai-core-api/comms",
          label: "Open an SSE channel for MCP tool communications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insight-data",
          label: "Process insight data and stream incremental plain text output",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Engine Execution",
      items: [
        {
          type: "doc",
          id: "ai-core-api/add-engine",
          label: "Add engine (placeholder)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/print-engines",
          label: "List engines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-auto-complete-results",
          label: "Autocomplete insights",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-search-insights-results",
          label: "Search insights",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/comet-try",
          label: "Start a comet job (legacy)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/console",
          label: "Get async job console logs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/download-file",
          label: "Download exported file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/error",
          label: "Get async job error logs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-pixel-pipeline-plan",
          label: "Get Pixel pipeline plan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/print-url",
          label: "Help routes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/kill-job",
          label: "Kill comet job (legacy)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-job-output",
          label: "Get comet job output (legacy)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-media-wiki-tags-for-search-term",
          label: "Search MediaWiki tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/partial",
          label: "Get async job partial output",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-play-sheets",
          label: "List available PlaySheets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/reset",
          label: "Reset async job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/result",
          label: "Get async job result",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/run-pixel-sync",
          label: "Execute Pixel synchronously",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/run-pixel-async",
          label: "Execute Pixel asynchronously",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/run-reactor-mcp",
          label: "runReactorMCP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/status",
          label: "Get async job status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/terminate",
          label: "Terminate async job",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "AI Models",
      items: [
        {
          type: "doc",
          id: "ai-core-api/run-model-chat-completion",
          label: "runModelChatCompletion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/run-model-completion",
          label: "runModelCompletion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/run-model-embeddings",
          label: "runModelEmbeddings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/list-models",
          label: "listModels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/retrieve-model",
          label: "retrieveModel",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Project",
      items: [
        {
          type: "doc",
          id: "ai-core-api/download-project-asset",
          label: "Download a project asset file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-embed-url",
          label: "Get embed logo for project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/download-insight-image",
          label: "Download insight image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-jdbc-output",
          label: "Execute SQL or pixel via JDBC bridge (binary)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-jdbccsv-output",
          label: "Execute SQL or pixel via JDBC bridge (CSV)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-jdbc-json-output",
          label: "Execute SQL or pixel via JDBC bridge (JSON)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-landing-page",
          label: "Get project landing page",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/download-project-image",
          label: "Download project image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-app-widget",
          label: "Download project widget file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/run-reactor",
          label: "Execute a reactor in the project context",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/update-smss-file-2",
          label: "Update a project SMSS file",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Scheduler",
      items: [
        {
          type: "doc",
          id: "ai-core-api/execute-pixel",
          label: "Execute Pixel (scheduler)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Session",
      items: [
        {
          type: "doc",
          id: "ai-core-api/get-active-sessions",
          label: "Get active sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/cancel-clean-session",
          label: "cancelCleanSession",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/clean-session",
          label: "Clean session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insights",
          label: "getInsights",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/invalidate-session",
          label: "invalidateSession",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Themes",
      items: [
        {
          type: "doc",
          id: "ai-core-api/create-admin-theme",
          label: "Create admin theme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-admin-theme",
          label: "Delete admin theme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-admin-theme",
          label: "Edit admin theme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-active-admin-theme",
          label: "Get active admin theme",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-admin-themes",
          label: "List admin themes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/set-active-admin-theme",
          label: "Set active admin theme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-all-admin-themes-inactive",
          label: "Set all admin themes inactive",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      items: [
        {
          type: "doc",
          id: "ai-core-api/change-ad-password",
          label: "changeADPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/create-api-user",
          label: "createAPIUser",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/create-native-user",
          label: "createNativeUser",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-login-properties",
          label: "getAllLoginProperties",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-native",
          label: "loginNative",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/login-adfs",
          label: "loginADFS",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-drop-box",
          label: "loginDropBox",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-github",
          label: "loginGithub",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-gitlab",
          label: "loginGitlab",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-google",
          label: "loginGoogle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-linkedin",
          label: "loginLinkedin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-microsoft",
          label: "loginMicrosoft",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-ms",
          label: "loginMS",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-okta",
          label: "loginOkta",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-producthunt",
          label: "loginProducthunt",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-salesforce",
          label: "loginSalesforce",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-siteminder",
          label: "loginSiteminder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-survey-monkey",
          label: "loginSurveyMonkey",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-twitter",
          label: "loginTwitter",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-generic",
          label: "loginGeneric",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/login-ldap",
          label: "loginLDAP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/login-lin-otp",
          label: "loginLinOTP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/login-properties",
          label: "loginProperties",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-logins",
          label: "Get available login providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/logins-allowed",
          label: "loginsAllowed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/logout",
          label: "Logout from specific provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/modify-all-login-properties",
          label: "modifyAllLoginProperties",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/modify-login-properties",
          label: "modifyLoginProperties",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/reset-lin-otp-fail-counter",
          label: "resetLinOTPFailCounter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-adfs",
          label: "userinfoADFS",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-dropbox",
          label: "userinfoDropbox",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-github",
          label: "userinfoGithub",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-google",
          label: "userinfoGoogle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-microsoft",
          label: "userinfoMicrosoft",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-ms",
          label: "userinfoMs",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-okta",
          label: "userinfoOkta",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/userinfo-generic",
          label: "userinfoGeneric",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/show",
          label: "Get current user information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "auth",
      items: [
        {
          type: "doc",
          id: "ai-core-api/add-all-users",
          label: "Add all users (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-app-user-permission",
          label: "Add app user permission (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-app-user-permission",
          label: "Edit app user permission (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-user-apps",
          label: "Get all user apps (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-app-users",
          label: "Get app users (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-app-users-no-credentials",
          label: "Get app users without credentials (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-apps",
          label: "Get apps (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-all-apps",
          label: "Grant all apps (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-new-users-app-access",
          label: "Grant new users app access (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-app-user-permission",
          label: "Remove app user permission (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-app-discoverable",
          label: "Set app discoverable (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-app-global",
          label: "Set app global (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/update-app-user-permissions",
          label: "Update app user permissions (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-all-users-1",
          label: "Add all users (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-database-user-permission",
          label: "Add database user permission (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-database-user-permissions",
          label: "Add database user permissions in bulk (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-database-user-access-request",
          label: "Approve database user access request (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-database-user-access-request",
          label: "Deny database user access request (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-database-user-permission",
          label: "Edit database user permission (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-database-user-permissions",
          label: "Edit database user permissions in bulk (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-user-databases",
          label: "Get all user databases (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-database-users",
          label: "Get database users (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-database-users-no-credentials",
          label: "Get database users without credentials (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-databases",
          label: "Get databases (legacy)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-all-databases",
          label: "Grant all databases (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-new-users-database-access",
          label: "Grant new users database access (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-database-user-permission",
          label: "Remove database user permission (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-database-user-permissions",
          label: "Remove database user permissions in bulk (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-database-discoverable",
          label: "Set database discoverable (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-database-global",
          label: "Set database global (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/update-database-user-permissions",
          label: "Update database user permissions (legacy)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-all-users-2",
          label: "Add all users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-engine-user-permission",
          label: "Add engine user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-engine-user-permissions",
          label: "Add engine user permissions (bulk)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-engine-user-access-request",
          label: "Approve engine user access request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-engine-user-access-request",
          label: "Deny engine user access request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-engine-user-permission",
          label: "Edit engine user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-engine-user-permissions",
          label: "Edit engine user permissions (bulk)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-user-engines",
          label: "Get all user engines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engine-users",
          label: "Get engine users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engine-users-no-credentials",
          label: "Get engine users without credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engines-get",
          label: "Get engines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engines-post",
          label: "Get engines (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-all-engines",
          label: "Grant all engines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-new-users-engine-access",
          label: "Grant new users engine access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-engine-user-permission",
          label: "Remove engine user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-engine-user-permissions",
          label: "Remove engine user permissions (bulk)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-engine-discoverable",
          label: "Set engine discoverable",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-engine-global",
          label: "Set engine global",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/update-engine-user-permissions",
          label: "Update engine user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group",
          label: "Create a group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group-engine-permission",
          label: "Grant engine permission to group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group-member",
          label: "Add group member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group-project-permission",
          label: "Grant project permission to group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-group",
          label: "Delete a group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-group-member",
          label: "Remove group member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group",
          label: "Edit a group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group-details",
          label: "Edit group details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group-engine-permission",
          label: "Edit engine permission for group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group-project-permission",
          label: "Edit project permission for group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-available-engines-for-group",
          label: "List available engines for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-available-projects-for-group",
          label: "List available projects for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engines-for-group",
          label: "List engines for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-group-members",
          label: "List group members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-groups",
          label: "List groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-non-group-members",
          label: "List non-members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-available-engines-for-group",
          label: "Count available engines for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-available-projects-for-group",
          label: "Count available projects for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-engines-for-group",
          label: "Count engines for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-members-in-group",
          label: "Count group members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-non-members-in-group",
          label: "Count non-members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-projects-for-group",
          label: "Count projects for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-projects-for-group",
          label: "List projects for group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-group-engine-permission",
          label: "Revoke engine permission from group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-group-project-permission",
          label: "Revoke project permission from group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-all-users-3",
          label: "Add all users to an insight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-insight-user-permission",
          label: "Add insight user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-insight-user-permissions",
          label: "Add multiple insight user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-insight-user-access-request",
          label: "Approve insight user access requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-project-insights",
          label: "Delete project insights",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-insight-user-access-request",
          label: "Deny insight user access requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-insight-user-permission",
          label: "Edit insight user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-insight-user-permissions",
          label: "Edit multiple insight user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-project-insight-users",
          label: "List project insight users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insight-users",
          label: "List insight users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insight-users-no-credentials",
          label: "List users without insight access",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insights-1",
          label: "List insights",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-insights",
          label: "List project insights",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-all-project-insights",
          label: "Grant all project insights",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-new-users-insight-access",
          label: "Grant new users insight access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-insight-user-permission",
          label: "Remove insight user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-insight-user-permissions",
          label: "Remove multiple insight user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-insight-global",
          label: "Set insight visibility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/update-app-user-permissions-1",
          label: "Update all insight user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-all-users-4",
          label: "Add all users to project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-project-user-permission",
          label: "Add project user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-project-user-permissions",
          label: "Add multiple project user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-project-user-access-request",
          label: "Approve project user access requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-project-user-access-request",
          label: "Deny project user access requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-project-user-permission",
          label: "Edit project user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-project-user-permissions",
          label: "Edit multiple project user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-user-projects",
          label: "List a user's projects",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-users",
          label: "List project users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-users-no-credentials",
          label: "List users without project access",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-projects-get",
          label: "List projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-projects-post",
          label: "List projects (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-all-projects",
          label: "Grant all projects",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/grant-new-users-project-access",
          label: "Grant new users project access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-project-user-permission",
          label: "Remove project user permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-project-user-permissions",
          label: "Remove multiple project user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-discoverable",
          label: "Set project discoverability",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-global",
          label: "Set project visibility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-portal",
          label: "Set project portal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/update-project-user-permissions",
          label: "Update all project user permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-user",
          label: "Delete user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-user",
          label: "Edit user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-all-db-users",
          label: "List users (deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/search-term",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-num-users",
          label: "Get number of users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/is-admin-user",
          label: "Check if current user is admin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/register-user",
          label: "Register a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-user-locked",
          label: "Set user lock status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-user-publisher",
          label: "Set user publisher flag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-app-user-permission-1",
          label: "[LEGACY] Add app user permission",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-app-user-permission-1",
          label: "[LEGACY] Edit app user permission",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-app-users-1",
          label: "[LEGACY] List app users",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-app-users-no-credentials-1",
          label: "[LEGACY] List users without app access",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-apps",
          label: "[LEGACY] List apps (databases)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-app-permission",
          label: "[LEGACY] Get user app permission",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-app-user-permission-1",
          label: "[LEGACY] Remove app user permission",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-app-discoverable-1",
          label: "[LEGACY] Set app discoverable",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-app-favorite",
          label: "[LEGACY] Set app favorite",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-app-global-1",
          label: "[LEGACY] Set app global visibility",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-app-visibility",
          label: "[LEGACY] Set app visibility",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-database-user-permission-1",
          label: "[LEGACY] Add database user permission",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-database-user-permissions-1",
          label: "[LEGACY] Add database user permissions (bulk)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-database-user-access-request-1",
          label: "[LEGACY] Approve database user access requests",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-database-user-access-request-1",
          label: "[LEGACY] Deny database user access requests",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-database-user-permission-1",
          label: "[LEGACY] Edit database user permission",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-database-user-permissions-1",
          label: "[LEGACY] Edit database user permissions (bulk)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-database-users-1",
          label: "[LEGACY] List database users",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-database-users-no-credentials-1",
          label: "[LEGACY] List users without database access",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-databases-1",
          label: "[LEGACY] List databases",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-database-permission",
          label: "[LEGACY] Get user database permission",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-database-user-permission-1",
          label: "[LEGACY] Remove database user permission",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-database-user-permissions-1",
          label: "[LEGACY] Remove database user permissions (bulk)",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-database-discoverable-1",
          label: "[LEGACY] Set database discoverable",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-database-favorite",
          label: "[LEGACY] Set database favorite",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-database-global-1",
          label: "[LEGACY] Set database global visibility",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-database-visibility",
          label: "[LEGACY] Set database visibility",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-engine-user-permission-1",
          label: "Grant engine access to a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-engine-user-permissions-1",
          label: "Grant engine access to multiple users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-engine-user-access-request-1",
          label: "Approve user access requests for an engine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-engine-user-access-request-1",
          label: "Deny user access requests for an engine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-engine-user-permission-1",
          label: "Edit a user's engine permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-engine-user-permissions-1",
          label: "Edit multiple users' engine permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engine-users-1",
          label: "List engine users and permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engine-users-no-credentials-1",
          label: "List users without access to an engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engines",
          label: "List engines available to the user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-engines-post-1",
          label: "List engines (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-engine-permission",
          label: "Get current user's permission for an engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-engine-user-permission-1",
          label: "Remove a user's engine access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-engine-user-permissions-1",
          label: "Remove multiple users' engine access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-engine-discoverable-1",
          label: "Set engine discoverable flag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-engine-favorite",
          label: "Set engine favorite flag for the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-engine-global-1",
          label: "Set engine global visibility (public/private)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-engine-visibility",
          label: "Set engine visibility for the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group-engine-permission-1",
          label: "Add group permission to an engine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group-app-permission",
          label: "Edit group permission for an app",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-group-app-permission",
          label: "Get group permission for an app/engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-group-app-permission",
          label: "Remove group permission for an app",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group-insight-permission",
          label: "Add group permission to an insight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group-insight-permission",
          label: "Edit group permission for an insight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-group-insight-permission",
          label: "Get group permission for an insight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-group-insight-permission",
          label: "Remove group permission for an insight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-group-project-permission-1",
          label: "Add group permission to a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-group-project-permission-1",
          label: "Edit group permission for a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-group-project-permission",
          label: "Get group permission for a project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-group-project-permission-1",
          label: "Remove group permission for a project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-insight-user-permission-1",
          label: "Grant insight access to a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-insight-user-permissions-1",
          label: "Grant insight access to multiple users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-insight-user-access-request-1",
          label: "Approve user access requests for an insight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-insight-user-access-request-1",
          label: "Deny user access requests for an insight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-insight-user-permission-1",
          label: "Edit a user's insight permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-insight-user-permissions-1",
          label: "Edit multiple users' insight permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insight-users-1",
          label: "List insight users and permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insight-users-no-credentials-1",
          label: "List users without access to an insight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-insights-2",
          label: "List insights available to the user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-insights-1",
          label: "List project insights the user can edit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-insight-permission",
          label: "Get current user's permission for an insight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-insight-user-permission-1",
          label: "Remove a user's insight access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-insight-user-permissions-1",
          label: "Remove multiple users' insight access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-insight-favorite",
          label: "Set insight favorite flag for the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-insight-global-1",
          label: "Set insight global visibility (public/private)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-project-user-permission-1",
          label: "addProjectUserPermission_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/add-project-user-permissions-1",
          label: "addProjectUserPermissions_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/approve-project-user-access-request-1",
          label: "approveProjectUserAccessRequest_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/deny-project-user-access-request-1",
          label: "denyProjectUserAccessRequest_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-project-user-permission-1",
          label: "editProjectUserPermission_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-project-user-permissions-1",
          label: "editProjectUserPermissions_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-users-1",
          label: "getProjectUsers_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-project-users-no-credentials-1",
          label: "getProjectUsersNoCredentials_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-projects-get-1",
          label: "getProjectsGET_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/get-projects-post-1",
          label: "getProjectsPOST_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-project-permission",
          label: "getUserProjectPermission",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/propagate-project-dependency-permission",
          label: "propagateProjectDependencyPermission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-project-user-permission-1",
          label: "removeProjectUserPermission_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/remove-project-user-permissions-1",
          label: "removeProjectUserPermissions_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-discoverable-1",
          label: "setProjectDiscoverable_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-favorite",
          label: "setProjectFavorite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-global-1",
          label: "setProjectGlobal_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-portal-1",
          label: "setProjectPortal_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/set-project-visibility",
          label: "setProjectVisibility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/create-user-access-key",
          label: "createUserAccessKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-user-1",
          label: "deleteUser_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/delete-user-access-key",
          label: "deleteUserAccessKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/edit-user-1",
          label: "editUser_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/get-user-access-keys",
          label: "getUserAccessKeys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ai-core-api/reset-password",
          label: "resetPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "ai-core-api/setup-reset-password",
          label: "setupResetPassword",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
